theme: jekyll-theme-minimal
title: AUSPOL Meta Spend 2025
description: Reporting the Meta digital advertising spend of 2025 federal election candidates. This page won't work if you've asked your browser not to track you.
